# C#尝试/捕捉

> 原文:[https://www.javatpoint.com/c-sharp-try-catch](https://www.javatpoint.com/c-sharp-try-catch)

在 C#编程中，异常处理由 try/catch 语句执行。C#中的 **try 块**用来放置可能抛出异常的代码。**捕捉块**用于处理异常。catch 块的前面必须有 try 块。

### 没有 try/catch 的 C#示例

```
using System;
public class ExExample
{
    public static void Main(string[] args)
    {
        int a = 10;
        int b = 0;
        int x = a/b;  
        Console.WriteLine("Rest of the code");
    }
}

```

输出:

```
Unhandled Exception: System.DivideByZeroException: Attempted to divide by zero.

```

### C#尝试/捕捉示例

```
using System;
public class ExExample
{
    public static void Main(string[] args)
    {
        try
        {
            int a = 10;
            int b = 0;
            int x = a / b;
        }
        catch (Exception e) { Console.WriteLine(e); }

        Console.WriteLine("Rest of the code");
    }
}

```

输出:

```
System.DivideByZeroException: Attempted to divide by zero.
Rest of the code

```