# 使用失败关键字抛出异常

> 原文:[https://www . javatpoint . com/f-sharp-throw-exception-using-fail with-keyword](https://www.javatpoint.com/f-sharp-throwing-exception-using-failwith-keyword)

在 F#中，可以显式抛出异常。您可以抛出自定义异常。您还可以通过使用预定义的异常方法(如失败和无效)来抛出异常。
Failwith 关键字生成系统。异常异常。它有 Failure 关键字来引用异常。我们来看一个例子。

```

let TestAgeValidation age  =
  try
     if (age<18) then failwith "Sorry, Age must be greater than 18"
  with
     | Failure(e) -> printfn "%s" e; 
  printf "Rest of the code"
TestAgeValidation 10

```

输出:

```
Sorry, Age must be greater than 18
Rest of the code

```

* * *

## 使用无效的关键字抛出异常

它生成 System.ArgumentException。您可以使用 InvalidArg 引发参数类型异常。我们来看一个例子。

```

let TestInvalidArgument age =
 if(age<18) then
  invalidArg "TestInvalidArgument" ("Sorry, Age must be greater than 18")

TestInvalidArgument 10

```

输出:

```
System.ArgumentException: Sorry, Age must be greater than 18

```